### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by shaharmor** [gamenet/redis-memory-analyzer#16]
Hi,

Trying to install on ubuntu 14.04:

```
Downloading/unpacking rma
  Downloading rma-0.1.5.tar.gz
  Running setup.py (path:/tmp/pip_build_root/rma/setup.py) egg_info for package rma
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/rma/setup.py", line 47
        setup(**sdict, install_requires=['redis', 'tabulate', 'tqdm', 'msgpack-python'])
                     ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/rma/setup.py", line 47

    setup(**sdict, install_requires=['redis', 'tabulate', 'tqdm', 'msgpack-python'])

                 ^

SyntaxError: invalid syntax

----------------------------------------
```

**Comment by misterion** [comment]
Could you provide your pip and python version?

**Comment by shaharmor** [comment]
```
# python -V
Python 3.4.3
# pip3 -V
pip 1.5.4 from /usr/lib/python3/dist-packages (python 3.4)
```

It also happens when i manually clone the repo

**Comment by mjpieters** [comment]
This is invalid syntax on any Python version; you can't put `**kwargs` keyword argument expansion in front of other keyword arguments. Swap the two:

    setup(install_requires=['redis', 'tabulate', 'tqdm', 'msgpack-python'], **sdict)

**Comment by misterion** [comment]
@mjpieters tnx for help! @shaharmor could you try with 0.1.6 ?

**Comment by shaharmor** [comment]
Now it requests for the `msgpack` module (Which isn't listed as a requirement).

After installing `msgpack-python` manually it asked for `tqdm` (Also not listed..)
Then it asked for `tabulate`...

and only then it finished successfully.

Can't you make it that it will automatically install it?

**Comment by misterion** [comment]
@mjpieters could i ask you help again? Now in setup args `install_requires` listed all requred components - 'redis', 'tabulate', 'tqdm', 'msgpack-python'. Also i see it in rma.egg-info requires.txt. But they do not install. Why?

**Comment by misterion** [comment]
@shaharmor i move all **kwargs as args. please test it with 0.1.7.

**Comment by mjpieters** [comment]
The `install_requires` looks correct to me but take into account only tools like `easy_install` and `pip` will go and fetch those requirements. If you run `python setup.py install` then you'll need to install the requirements manually.

**Comment by mjpieters** [comment]
Hrm, I can confirm the package still doesn't install with `pip` either.

**Comment by mjpieters** [comment]
Ah, you do `from rma import __version__` and that then loads `rma/__init__.py`, which starts loading everything else, including `from rma.application import RmaApplication` which then imports `from rma.scanner import Scanner` and `scanner.py` has `import msgpack`.

Don't import your package in `setup.py`.

**Comment by mjpieters** [comment]
You could look at [What is the correct way to share package version with setup.py and the package?](http://stackoverflow.com/q/17583443/100297) for an alternative method of sharing the version between setup.py and the package.

**Comment by misterion** [comment]
Tnx a lot @mjpieters !
