### ISSUE TITLE
WARNING:rma.rule.ValueString:ResponseError("unknown command 'DEBUG'",)

### ISSUE THREAD

**Issue by comjf** [gamenet/redis-memory-analyzer#21]
I'm running on python 3.5 and I installed RMA from this source code directly. If I run something like
```
rma -s <instance> -d 6 -b scanner
```
I see proper results, but when specifying other 'behaviors' or even not specifying that flag all yield the same error message:
```
Aggregating keys by pattern and type

Apply rules
WARNING:rma.rule.GlobalKeySpace:*max* option skipped: ResponseError("unknown command 'CONFIG'",)
Processing String patterns:   0%|                                                                                                                                                | 0/164933 [00:00<?, ?it/s]WARNING:rma.rule.ValueString:ResponseError("unknown command 'DEBUG'",)
WARNING:rma.rule.ValueString:ResponseError("unknown command 'DEBUG'",)
....
```

And that warning repeats itself (maybe once for ever key?).

I'm using this on AWS's ElastiCache running redis 2.8.22 on a debug instance I created from a snapshot. Is amazon preventing this debug command from being executed somehow?? I checked the parameter group settings and couldn't find an option that looked like it matched. Any advise? 

Thanks!
James Flowers

**Comment by misterion** [comment]
Yes, CONFIG issue is not supported on most of clous solustion and was fixed as part of #3. Warining in GlobalKeySpace just inform about this issue. `DEBUG SDSLEN` was added to Redis 2.8.5 and should be available. Could you check it by hands on your Redis instanse? If not supported on AWS's ElastiCache i`l do a workaround to calculate string size without it.

**Comment by comjf** [comment]
@misterion Thank you for the quick reply, nothing I tried worked (Let me know if I'm doing the wrong command)

```
<instance>:6379> select 5
OK
<instance>:6379[5]> RANDOMKEY
"ww-identity_cache:IDC:5:blob:ZipCodeLookup:3933566624995091082:06036"
(0.75s)
<instance>:6379[5]> DEBUG ww-identity_cache:IDC:5:blob:ZipCodeLookup:3933566624995091082:06036
(error) ERR unknown command 'DEBUG'
(0.90s)
<instance>:6379[5]> DEBUG SDSLEN ww-identity_cache:IDC:5:blob:ZipCodeLookup:3933566624995091082:06036
(error) ERR unknown command 'DEBUG'
<instance>:6379[5]> DEBUG OBJECT ww-identity_cache:IDC:5:blob:ZipCodeLookup:3933566624995091082:06036
(error) ERR unknown command 'DEBUG'
```

What is the other way to calculate size?

**Comment by misterion** [comment]
@comjf it looks like AWS's ElastiCache do not support `DEBUG` at all. So i think i`l add some code to check this and rewrite rule to work with modes then this command allowed and disallowed.

**Comment by comjf** [comment]
@misterion Perfect! Let me know if you need any help, I can test your updated code when ready.

Thank you!

**Comment by misterion** [comment]
I think i fix it in 0.1.11. Could you test it please?

**Comment by comjf** [comment]
@misterion Thank you for the quick turn around!!

It appears to be working. I now see a summary of the keys with great information about them. I do think I've spotted another bug, I'm not sure if this is related but if you look at this
```
rma -s <instance>.use1.cache.amazonaws.com -d 6

| Stat                           | Value          |
|:-------------------------------|:---------------|
| Total keys in db               | 9              |
| RedisDB key space overhead     | 512            |
| Info `used_memory_rss`         | 22178394112    |
| Info `used_memory_human`       | 20.20G         |
| Info `used_memory_peak_human`  | 20.44G         |
| Info `used_memory_peak`        | 21947082536    |
| Info `mem_fragmentation_ratio` | 1.02           |
| Info `used_memory_lua`         | 1548288        |
| Info `mem_allocator`           | jemalloc-3.6.0 |
| Info `used_memory`             | 21694895216    |
```

You can see that there are only 9 keys in this database and they are all very small, yet this used_memory is really high. I think this metric is the entire redis memory, not specific to the DB I passed in the -d flag. Should I open this as a separate github issue?

**Comment by misterion** [comment]
This part of stat from global rule. Most of it from Redis INFO command. I'l check it in monday is it possible to separate info response per db.

**Comment by misterion** [comment]
@comjf http://redis.io/commands/info return information per server basis. So this part of stat is correct but may look like a bit confusing. I think i should write some more about this in readme.
